title: rspeare.github.io
theme: jekyll-theme-cayman
author: rspeare
email: robert.speare@gmail.com
description: Statistics and Code
twitter_username: waiting4spark
github_username:  rspeare
linkedin_username: rob-speare-aaa6834a
